apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-brukernotifikasjon
  namespace: teamnks
  labels:
    team: teamnks
spec:
  image: '{{ image }}'
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
    periodSeconds: 5
    failureThreshold: 5
  terminationGracePeriodSeconds: 40
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
  ingresses:
    - "https://sf-brukernotifikasjon-v2.ekstern.dev.nav.no"
    - "https://sf-brukernotifikasjon-v2.intern.dev.nav.no"
  envFrom:
    - secret: sf-brukernotifikasjon
  filesFrom:
    - secret: sf-brukernotifikasjon
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: salesforce
          namespace: teamcrm
          cluster: dev-external
        - application: saas-proxy
          namespace: teamcrm
  kafka:
    pool: nav-dev
  env:
    - name: KAFKA_CLIENTID
      value: sf-brukernotifikasjon
    - name: KAFKA_TOPIC_NYBESKJED
      value: 'min-side.aapen-brukernotifikasjon-nyBeskjed-v1'
    - name: KAFKA_TOPIC_NYOPPGAVE
      value: 'min-side.aapen-brukernotifikasjon-nyOppgave-v1'
    - name: KAFKA_TOPIC_DONE
      value: 'min-side.aapen-brukernotifikasjon-done-v1'
    - name: KAFKA_TOPIC_INNBOKS
      value: 'min-side.aapen-brukernotifikasjon-innboks-v1'
    - name: CONTEXT
      value: "DEV"
