apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-brukernotifikasjon
  namespace: teamnks
  labels:
    team: teamnks
spec:
  webproxy: true
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/prod/fss/sf-brukernotifikasjon/teamnks
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/prod/srvsfbrukernot
  env:
    - name: KAFKA_BROKERS
      value: SASL_SSL://a01apvl00145.adeo.no:8443,SASL_SSL://a01apvl00146.adeo.no:8443,SASL_SSL://a01apvl00147.adeo.no:8443,SASL_SSL://a01apvl00148.adeo.no:8443,SASL_SSL://a01apvl00149.adeo.no:8443,SASL_SSL://a01apvl00150.adeo.no:8443
    - name: KAFKA_CLIENTID
      value: sf-brukernotifikasjon-prod
    - name: KAFKA_SECURITY
      value: 'TRUE'
    - name: KAFKA_SECPROT
      value: SASL_SSL
    - name: KAFKA_SASLMEC
      value: PLAIN
    - name: KAFKA_TOPIC_ENDRET
      value: 'aapen-ngt'
    - name: KAFKA_TOPIC_OPPRETTET
      value: 'aapen-ngt2'
    - name: MS_BETWEEN_WORK
      value: '240000'
    - name: SF_INSTANCE
      value: PRODUCTION
    - name: SF_TOKENHOST
      value: 'https://login.salesforce.com'
    - name: SF_VERSION
      value: 'v48.0'
    - name: VAULT_INSTANCE
      value: PRODUCTION
