apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-brukernotifikasjon
  namespace: teamnks
  labels:
    team: teamnks
spec:
  webproxy: true
  image: {{ image }}
  port: 8080
  replicas:
    min: 2 # Guarantee of service at reboots etc
    max: 2
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  ingresses:
    - "https://sf-brukernotifikasjon.nav.no"
    - "https://sf-brukernotifikasjon-v2.intern.nav.no"
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: salesforce
          namespace: teamcrm
          cluster: prod-external
        - application: saas-proxy
          namespace: teamcrm
  kafka:
    pool: nav-prod
  env:
    - name: KAFKA_CLIENTID
      value: sf-brukernotifikasjon
    - name: KAFKA_TOPIC_NYBESKJED
      value: 'min-side.aapen-brukernotifikasjon-nyBeskjed-v1'
    - name: KAFKA_TOPIC_NYOPPGAVE
      value: 'min-side.aapen-brukernotifikasjon-nyOppgave-v1'
    - name: KAFKA_TOPIC_DONE
      value: 'min-side.aapen-brukernotifikasjon-done-v1'
    - name: KAFKA_TOPIC_INNBOKS
      value: 'min-side.aapen-brukernotifikasjon-innboks-v1'
    - name: MS_BETWEEN_WORK
      value: '240000'
    - name: SF_INSTANCE
      value: PRODUCTION
    - name: SF_TOKENHOST
      value: 'https://login.salesforce.com'
    - name: SF_VERSION
      value: 'v48.0'
    - name: VAULT_INSTANCE
      value: GCP
    - name: MS_BETWEEN_WORK
      value: "6000000"
