apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-brukernotifikasjon
  namespace: teamnks
  labels:
    team: teamnks
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 2
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
  ingresses:
    - "https://sf-brukernotifikasjon.nav.no"
    - "https://sf-brukernotifikasjon-v2.intern.nav.no"
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: salesforce
          namespace: teamcrm
          cluster: prod-external
        - application: saas-proxy
          namespace: teamcrm
  kafka:
    pool: nav-prod
  env:
    - name: KAFKA_CLIENTID
      value: sf-brukernotifikasjon
    - name: KAFKA_TOPIC_NYBESKJED
      value: 'min-side.aapen-brukernotifikasjon-nyBeskjed-v1'
    - name: KAFKA_TOPIC_NYOPPGAVE
      value: 'min-side.aapen-brukernotifikasjon-nyOppgave-v1'
    - name: KAFKA_TOPIC_DONE
      value: 'min-side.aapen-brukernotifikasjon-done-v1'
    - name: KAFKA_TOPIC_INNBOKS
      value: 'min-side.aapen-brukernotifikasjon-innboks-v1'
    - name: SF_INSTANCE
      value: PRODUCTION
