swagger: '2.0'
info:
  description: API for arkiv dokumentasjon
  version: '1.0'
  title: Arkiv dokumentasjon
basePath: /
tags:
  - name: arkiv-controller
    description: API for arkiv dokumentasjon
paths:
  /arkiv:
    post:
      tags:
        - arkiv-controller
      responses:
        '201':
          description: OK - arkivert
          schema:
            type: array
            items:
              $ref: '#/definitions/ArkivResponse'
        '401':
          description: Giltigt token saknas
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/ArkivModel'
      consumes:
        - application/json
definitions:
  ArkivModel:
    properties:
      dokumentasjon:
        type: string
      kilde:
        type: string
      opprettetAv:
        type: string
  ArkivResponse:
    properties:
      id:
        type: integer
        format: int32
      dato:
        type: string
      dokumentasjonSummarized:
        type: string
      kilde:
        type: string
      opprettetAv:
        type: string
